name: Continuous Integration
on:
  - pull_request
  - push
jobs:
  testing:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - "7.4"
          - "8.0"
          - "8.1"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Composer
        uses: ramsey/composer-install@v2

      - name: Running tests
        run: vendor/bin/phpunit